Repository uprm-inso4117-2024-2025-s2/semester-project-briscas, pull requests merged in 2025-02, with the labels that each got.

#69 Card
  models/Card.js
  tests/CardTest.js
Labels: game logic

#70 Implement Deck Class & Integrate with Card.js
  models/Deck.js
  tests/DeckTest.js
Labels: game logic

#71 Implement Shuffle and Draw Functions for Deck
  models/Deck.js
  tests/DeckTest.js
Labels: game logic

#72 Created trump card mechanics and added tester
  models/Card.js
  models/Deck.js
  tests/TrumpCardTest.js
Labels: [ Sub-Issue ]

#120 Implemented Profile Page UI
  Reactapp/react_app/index.html
  Reactapp/react_app/src/main.tsx
  Reactapp/react_app/src/pages/Profile.tsx
  Reactapp/react_app/src/styles/pages/Profile_Page.css
Labels: UI, Awaiting Verification ⏳

#123 Sub-issue #40: Validate player actions and prevent invalid moves
  models/Player.js
  tests/PlayerTest.js
Labels: game logic, Awaiting Verification ⏳

#118 includes gamemanager class
  models/GameManager.js
  models/Player.js
  tests/GameManagerTest.js
Labels: game logic, Awaiting Verification ⏳

#122 Added a class to handle the rendering of the cards
  .vscode/settings.json
  package.json
  visual_elements/VisualElements.js
Labels: UI, Awaiting Verification ⏳, completed
