Repository uprm-inso4117-2024-2025-s2/semester-project-briscas, pull requests merged in 2025-04, with the labels that each got.

#297 Add Disconnection Detection and Game Pausing Logic
  node_modules/.package-lock.json
  package-lock.json
  src/network/sessionManager.js
  src/network/socketServer.js
  tests/ConnectionsTest.js
Labels: game logic, completed

#311 Finished Visual Regression Testing
  tests/visualRegressionTest.js
Labels: Awaiting Verification ⏳

#313 Sub-Issue Multiplayer Join Session, Leave Session and Destroy Session #312 finished
  node_modules/.package-lock.json
  package-lock.json
  src/network/sessionManager.js
  src/network/socketServer.js
  tests/multiplayer_test.js
Labels: game logic, [ Sub-Issue ], Awaiting Verification ⏳

#314 Implement timeout and auto-pass system in GameState
  models/GameState.js
  tests/GameStateTimeoutTest.js
Labels: game logic, [ Main-Issue ]

#328 318 alloy model
  alloy-modeling/briscas_00_cards.als
  alloy-modeling/briscas_01_oneDeck.als
  alloy-modeling/briscas_02_multiDecks.als
  alloy-modeling/briscas_03_cardScores.als
Labels: documentation, LTT, [ Sub-Issue ], Awaiting Verification ⏳

#329 Code added for validactrion, and resyn in server. Includes load testing for both
  src/network/socketServer.js
  tests/load_test.js
Labels: lecture topic task, game logic

#332 Implemented rudimentary stryker testing and mocha orchestrator for mu…
  .gitignore
  models/EndScoreManager.js
  node_modules/.package-lock.json
  package-lock.json
  package.json
  tests/EndScoreManagerTest.js
Labels: game logic

#333 added missing files from last commit
  stryker.conf.js
  tests/legacy-tests.js
Labels: game logic, Manager Approved 👍

#343 Refactor AI test files to run in plain Node.js without Mocha/Chai
  tests/AIEasyTest.js
  tests/AIHardTest.js
  tests/AINormalTest.js
Labels: lecture topic task, game logic

#347 Issue #250 Multiplayer GameSession Manager
  src/network/sessionManager.js
  src/network/socketServer.js
Labels: game logic, [ Main-Issue ]
