Repository uprm-inso4117-2024-2025-s2/semester-project-briscas, pull requests merged in 2025-03, with the labels that each got.

#155 Feature/ai gamestate sync
  models/ai/BriscaAI.js
  tests/AITest.js
Labels: game logic

#167 [Lecture Topic Task] Performance Testing Plan for Briscas Game
  models/GameManager.js
  models/ai/AIPlayerold.js
  tests/GManagerPerformance.js
  tests/PerformanceTest.js
Labels: documentation, game logic

#185 Gameboard
  Reactapp/react_app/src/assets/briscas3.jpg
  Reactapp/react_app/src/components/Navbar.tsx
  Reactapp/react_app/src/main.tsx
  Reactapp/react_app/src/pages/GameBoard.tsx
  Reactapp/react_app/src/pages/Home.tsx
  Reactapp/react_app/src/styles/pages/GameBoard.css
Labels: UI

#157 AI Easy Mode Difficulty
  models/ai/AIPlayerModel.js
  tests/AIEasyTest.js
Labels: game logic, [ Sub-Issue ], Awaiting Verification ⏳

#214 Implement AIHard Class and Tests
  models/ai/AIEasy.js
  models/ai/AIHard.js
  models/ai/AIPlayerModel.js
  node_modules/.package-lock.json
  package-lock.json
  package.json
  tests/AIEasyTest.js
  tests/AIHardTest.js
Labels: game logic, [ Sub-Issue ], [ Main-Issue ]

#226 Added AI GameState Stress Test to evaluate performance and stability LTT
  tests/GameStateAIStressTest.js
Labels: LTT, game logic

#228 Normal AI implementation with a regular test case and Performance test results
  models/ai/AINormal.js
  tests/AINormalPerformanceTest.js
  tests/AINormalTest.js
Labels: LTT, game logic, [ Sub-Issue ], Awaiting Verification ⏳

#224 Display Cards on Gameboard with Backend functionality
  Reactapp/react_app/public/assets/back.png
  Reactapp/react_app/public/assets/cards/bastos_1.png
  Reactapp/react_app/public/assets/cards/bastos_10.png
  Reactapp/react_app/public/assets/cards/bastos_11.png
  Reactapp/react_app/public/assets/cards/bastos_12.png
  Reactapp/react_app/public/assets/cards/bastos_2.png
  Reactapp/react_app/public/assets/cards/bastos_3.png
  Reactapp/react_app/public/assets/cards/bastos_4.png
  Reactapp/react_app/public/assets/cards/bastos_5.png
  Reactapp/react_app/public/assets/cards/bastos_6.png
  Reactapp/react_app/public/assets/cards/bastos_7.png
  Reactapp/react_app/public/assets/cards/copas_1.png
  Reactapp/react_app/public/assets/cards/copas_10.png
  Reactapp/react_app/public/assets/cards/copas_11.png
  Reactapp/react_app/public/assets/cards/copas_12.png
  Reactapp/react_app/public/assets/cards/copas_2.png
  Reactapp/react_app/public/assets/cards/copas_3.png
  Reactapp/react_app/public/assets/cards/copas_4.png
  Reactapp/react_app/public/assets/cards/copas_5.png
  Reactapp/react_app/public/assets/cards/copas_6.png
  Reactapp/react_app/public/assets/cards/copas_7.png
  Reactapp/react_app/public/assets/empty_card.png
  Reactapp/react_app/src/pages/GameBoard.tsx
  Reactapp/react_app/src/styles/pages/GameBoard.css
  visual_elements/VisualElements.d.ts
  visual_elements/VisualElements.js
Labels: Awaiting Verification ⏳

#240 Fixed update and edit profile buttons for Profile Page
  Reactapp/react_app/src/pages/Profile.tsx
  Reactapp/react_app/src/styles/pages/Profile_Page.css
Labels: UI, Awaiting Verification ⏳
